version: '3.9'

services:
  ntt:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5001:5001"

  postgres:
    image: postgres:14.2
    healthcheck:
      test: [ "CMD", "pg_isready"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    env_file:
      - .env
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    expose:
      - "5432"

networks:
  default:
    name: transit